# Generated by Django 4.0.3 on 2022-11-22 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=50)),
                ('PICTURE', models.ImageField(default='static/img/team/download.png', upload_to='profilephoto')),
                ('DEPARTMENT', models.CharField(choices=[('select', 'select'), ('CS Department', 'CS Department'), ('E&C Department', 'E&C Department'), ('Mechanical Department', 'Mechanical Department'), ('Civil Department', 'Civil Department'), ('AI&ML Department', 'AI&ML Department'), ('Robotics and AIML Department', 'Robotics and AIML Department'), ('MBA', 'MBA'), ('Material Science and Engineering', 'Material Science and Engineering')], default='select', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
