# Generated by Django 4.0.3 on 2022-11-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='USN',
        ),
    ]
