# Generated by Django 4.0.3 on 2022-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_usn_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PICTURE',
            field=models.ImageField(default='static/img/team/download.png', upload_to='static/profilephoto'),
        ),
    ]
