# Generated by Django 4.0.3 on 2022-11-22 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
