# Generated by Django 4.0.3 on 2022-11-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_alter_noticeboard_engineering_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard_engineering',
            name='date_and_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
