# Generated by Django 4.0.3 on 2022-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_alter_noticeboard_engineering_date_and_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeboard_engineering',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='noticeboard_engineering',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
