# Generated by Django 4.0.3 on 2022-11-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_remove_noticeboard_engineering_date_and_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=1000)),
                ('Image', models.ImageField(upload_to='Engineeringimage')),
                ('Image2', models.ImageField(blank=True, upload_to='Engineeringimage')),
                ('Image3', models.ImageField(blank=True, upload_to='Engineeringimage')),
                ('Image4', models.ImageField(blank=True, upload_to='Engineeringimage')),
                ('Image5', models.ImageField(blank=True, upload_to='Engineeringimage')),
                ('Image6', models.ImageField(blank=True, upload_to='Engineeringimage')),
            ],
        ),
    ]
