# Generated by Django 4.0.3 on 2022-11-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_events_date_alter_events_image_alter_events_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='discription',
            field=models.CharField(max_length=10000),
        ),
    ]
